version: "3.7"

services:
  php73-xdebug:
    image: docker.pkg.github.com/fernandomiguel/php/php:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}-xdebug
    build:
      context: ./php
      dockerfile: Dockerfile-7.3
      target: php73-xdebug

  nodeapp:
    image: docker.pkg.github.com/fernandomiguel/nodeapp/nodeapp:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./nodeapp
      dockerfile: Dockerfile-node

  pythonapp:
    image: docker.pkg.github.com/fernandomiguel/pythonapp/pythonapp:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./pythonapp
      dockerfile: Dockerfile-python

  pythonapp-nginx:
    image: docker.pkg.github.com/fernandomiguel/pythonapp/pythonapp-nginx:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./pythonapp
      dockerfile: Dockerfile-nginx
      args:
        - NGINX_BASE_IMAGE=docker.pkg.github.com/fernandomiguel/nginx-base/nginx-base:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
