version: "3.7"

services:
  php73-xdebug:
    image: php-xdebug:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./php
      dockerfile: Dockerfile-7.3-xdebug
      args:
        - PHP_BASE_IMAGE=php:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
