version: "3.7"

services:
  php73:
    image: php:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./php
      dockerfile: Dockerfile-7.3
      args:
        - AWS_ECR_ACCOUNT=${AWS_ECR_ACCOUNT:-0123456789}

  php73-xdebug:
    image: php-xdebug:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./php
      dockerfile: Dockerfile-7.3-xdebug
      args:
        - PHP_BASE_IMAGE=php:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}

  nginx-base:
    image: nginx-base:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./nginx
      dockerfile: Dockerfile

  nodeapp:
    image: nodeapp:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}
    build:
      context: ./nodeapp
      dockerfile: Dockerfile-node
