name: Docker in Docker

on:
  push:
    branches:
    - did/*

jobs:
  build-docker-compose:
    name: test DinD
    runs-on: ubuntu-latest
    steps:
      # volumes:
      #   - my_docker_volume:/volume_mount
    - name: docker version
      uses: docker://docker/compose:1.25.0-rc2
      with:
        args: docker version

    - name: checkout
      uses: actions/checkout@v1 # --quiet
      with:
        fetch-depth: 1
        quiet: true

    - name: docker-compose build
      env:
        LLB: docker-build
      uses: docker://docker/compose:1.25.0-rc2
      with:
        args: docker-compose -f docker-compose.yml -f docker-compose.stage-2.yml config

    #     echo "Building images"
    #     # docker-compose build --parallel  ##  old version on the gihub action node, prevent us from using --parallel
    #     docker-compose build

    #     echo "Building images that depend on the previous stage"
    #     docker-compose -f docker-compose.stage-2.yml build

    #     echo "Show tagged images"
    #     docker images
