name: test merge

on:
  push:
    branches:
    - mergeyaml/*

jobs:
  dockerbuild:
    name: docker build
    runs-on: ubuntu-latest

    steps:
    - name: dockerbuild
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT: 1
        PREFER_BUILDCTL: 1
      run: |
        docker version
        docker info
        mkdir -p ~/.docker/cli-plugins/
        export PATH=~/.docker/cli-plugins/:$PATH
        git clone -b group-merge --single-branch https://github.com/tonistiigi/buildx.git
        cd buildx
        docker build --platform=local -o .
        mv buildx ~/.docker/cli-plugins/docker-buildx
        docker-buildx version

    - name: checkout
      uses: actions/checkout@v1

    - name: merge 1
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        PREFER_BUILDCTL: 1
        DOCKER_BUILDKIT: 1
      run: |
        export PATH=~/.docker/cli-plugins/:$PATH
        docker-compose -f docker-compose.yml -f buildx.yml config
        docker-buildx bake -f docker-compose.yml -f buildx.yml --print
        # docker-buildx bake -f docker-compose.yml -f buildx.yml
        # docker images

    - name: merge 2
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        PREFER_BUILDCTL: 1
        DOCKER_BUILDKIT: 1
      run: |
        export PATH=~/.docker/cli-plugins/:$PATH
        docker-compose -f docker-compose.yml -f buildx.1.yml config
        docker-buildx bake -f docker-compose.yml -f buildx.1.yml --print
        # docker-buildx bake -f docker-compose.yml -f buildx.yml
        # docker images
